export const ADD_EDUCATION_ITEM = 'ADD_EDUCATION_ITEM';
export const ADD_EXPERIENCE_ITEM = 'ADD_EXPERIENCE_ITEM';
export const ADD_SKILL_ITEM = 'ADD_SKILL_ITEM';
export const ADD_PERSONAL_INFO_ITEM = 'ADD_PERSONAL_INFO_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'